### ISSUE TITLE
need to push the latest version on pypi

### ISSUE THREAD

**Issue by charbu** [MarineDataTools/pycnv#5]
Hi, the current version available on pypi is 0.4.2 while the latest code version is 4.2.8
Can you upload the latest version on pypi ?
Thanks 🙏

**Comment by pholter** [comment]
Yes thank, I will do that.

**Comment by pholter** [comment]
Hi, I have uploaded the package. Would be nice if you could test the result. Best wishes.

**Comment by charbu** [comment]
It works like a charm. Thanks again!
